name: flutter_advanced_segment
description: An advanced segment widget, that can be fully customized with bunch of properties, just try it and enjoy!
version: 2.0.0
homepage: https://github.com/alex-melnyk/flutter_advanced_segment
repository: https://github.com/alex-melnyk/flutter_advanced_segment
issue_tracker: https://github.com/alex-melnyk/flutter_advanced_segment/issues
documentation: https://github.com/alex-melnyk/flutter_advanced_segment/blob/master/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
